---
- name: install python-pycurl
  apt: pkg=python-pycurl

- name: percona apt repository key
  apt_key: id=CD2EFD2A url=http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona

- name: percona apt repository
  apt_repository: repo='deb http://repo.percona.com/apt precise main' update_cache=yes cache_valid_time=3600
