---
- name: create ceilometer user
  user: name=ceilometer comment=ceilometer shell=/bin/false system=yes home=/nonexistent
        createhome=no

- name: create ceilometer environment.d directory
  file: dest=/etc/ceilometer/environment.d state=directory

- name: create ceilometer log directory
  file: dest=/var/log/ceilometer state=directory mode=0755 owner=ceilometer

- name: create ceilometer cache dir
  file: dest=/var/cache/ceilometer state=directory mode=0700
        owner=ceilometer group=ceilometer

- name: ceilometer config
  template: src=etc/ceilometer/{{ item }} dest=/etc/ceilometer/{{ item }} mode=0644
  with_items:
    - ceilometer.conf
    - policy.json
    - api_paste.ini
    - event_definitions.yaml
    - event_pipeline.yaml
    - pipeline.yaml
    - ceilometer_api_audit_map.conf

- include: logging.yml
  tags:
    - logrotate
    - logging
  when: logging.enabled|default('True')|bool

- include: serverspec.yml
  tags:
    - serverspec
  when: serverspec.enabled|default('False')|bool
