---
cinder:
  rev: 7b1d7a31335bd8723551c9af5c270927ad830c3f
  enabled_backends: None
  default_backend: None
  backends: []

  logs:
  - paths:
      - /var/log/cinder/cinder-api.log
    fields:
      type: openstack
      tags: cinder,cinder-api
  - paths:
      - /var/log/cinder/cinder-manage.log
    fields:
      type: openstack
      tags: cinder,cinder-manage
  - paths:
      - /var/log/cinder/cinder-scheduler.log
    fields:
      type: openstack
      tags: cinder,cinder-scheduler
  - paths:
      - /var/log/upstart/tgt.log
    fields:
      type: openstack
      tags: cinder,tgt
