---
keystone:
  token_expiration_in_seconds: 86400
  admin_workers: 5
  public_workers: 5
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: babel, version: 1.3 }
      - { name: mysql-python }
      - { name: functools32 }
    system_dependencies:
      - openssl
      - libldap2-dev
      - libsasl2-dev
      - libkrb5-dev
      - libmysqlclient-dev
  alternatives:
    - keystone-manage
    - keystone-all
  jellyroll: False # custom middleware for password compliance
  logs:
    - paths:
      - /var/log/keystone/keystone-all.log
      fields:
        type: openstack
        tags: keystone,keystone-all
    - paths:
        - /var/log/keystone/keystone-manage.log
      fields:
        type: openstack
        tags: keystone,keystone-manage
  logging:
    debug: False
    verbose: True
