---
keystone:
  rev: db291b340e63b74d8d240abfc37d03fb163f33f1
  token_expiration_in_seconds: 86400
  admin_workers: 5
  public_workers: 5

  logs:
    - paths:
      - /var/log/keystone/keystone-all.log
      fields:
        type: openstack
        tags: keystone,keystone-all
    - paths:
        - /var/log/keystone/keystone-manage.log
      fields:
        type: openstack
        tags: keystone,keystone-manage
  logging:
    debug: {{ logging.debug }}
    verbose: {{ logging.verbose }}
