---
ironic:
  virtualenv: /opt/stack/ironic
  path: /opt/stack/ironic
  client_rev: e611ae5f206d846e72684ba16c345653232c45c3
  client_virtualenv: /opt/stack/python-ironicclient
  client_path: /opt/stack/python-ironicclient
  tftp_server: hostvars[inventory_hostname][primary_interface]['ipv4']['address']
  dns_server: hostvars[inventory_hostname][primary_interface]['ipv4']['address']
  api_url:
    scheme: http
    host: hostvars[inventory_hostname][primary_interface]['ipv4']['address']
    port: 6385
  tftpboot_path: /tftpboot
  enabled_drivers:
    - fake
    - pxe_ssh
    - pxe_ipmitool
  heartbeat_timeout_threshold: 30
  source:
    rev: 'stable/mitaka'
    constrain: True
    upper_constraints: 'https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt'
    python_dependencies:
      - { name: PyMySQL }
    system_dependencies: []
  alternatives:
    - ironic-api
    - ironic-conductor
    - ironic-dbsync
    - ironic-nova-bm-migrate
    - ironic-rootwrap
  logs:
    - paths:
        - /var/log/ironic/ironic-api.log
      fields:
        type: openstack
        tags: ironic,ironic-api
    - paths:
        - /var/log/ironic/ironic-conductor.log
      fields:
        type: openstack
        tags: ironic,ironic-conductor
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
