---
swift:
  enabled: False
  logging:
    debug: False
  hash_path_prefix: a57b0dfd61b5fe3a
  disks:
    - disk: sdb
  allow_versions: True
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: keystonemiddleware }
      - { name: python-swiftclient }
  alternatives:
    - swift-account-audit
    - swift-account-auditor
    - swift-account-info
    - swift-account-reaper
    - swift-account-replicator
    - swift-account-server
    - swift-config
    - swift-container-auditor
    - swift-container-info
    - swift-container-reconciler
    - swift-container-replicator
    - swift-container-server
    - swift-container-sync
    - swift-container-updater
    - swift-dispersion-populate
    - swift-dispersion-report
    - swift-drive-audit
    - swift-form-signature
    - swift-get-nodes
    - swift-init
    - swift-object-auditor
    - swift-object-expirer
    - swift-object-info
    - swift-object-replicator
    - swift-object-server
    - swift-object-updater
    - swift-oldies
    - swift-orphans
    - swift-proxy-server
    - swift-recon
    - swift-reconciler-enqueue
    - swift-recon-cron
    - swift-ring-builder
    - swift-temp-url
  logs:
    - paths:
        - /var/log/swift/account.log
      fields:
        type: openstack
        tags: swift,swift-acount
    - paths:
        - /var/log/swift/container.log
      fields:
        type: openstack
        tags: swift,swift-container
    - paths:
        - /var/log/swift/object.log
      fields:
        type: openstack
        tags: swift,swift-object
    - paths:
        - /var/log/swift/proxy.log
      fields:
        type: openstack
        tags: swift,swift-proxy
    - paths:
        - /var/log/swift/swift.log
      fields:
        type: openstack
        tags: swift
  tuning:
      net.netfilter.nf_conntrack_max: 262144
      net.ipv4.tcp_syncookies: 0
      net.ipv4.tcp_tw_recycle: 1
      net.ipv4.tcp_tw_reuse: 1
