---
- name: nova process checks
  sensu_process_check: service={{ item }}
  with_items:
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
  notify: restart sensu-client

- name: nova-api process checks
  sensu_process_check: service=nova-api warn_over=20 crit_over=30
  notify: restart sensu-client

- name: nova-api check
  sensu_check: name=check-nova-api plugin=check-os-api.rb
               args="--service nova --criticality {{ nova.monitoring.sensu_checks.check_nova_api.criticality }}"
  notify: restart sensu-client

- name: check nova services
  sensu_check_dict:
    name: "check-nova-services"
    check: "{{ sensu_checks.nova.check_nova_services }}"
  notify: restart sensu-client missing ok

- name: nova metrics check
  sensu_metrics_check: name=nova-metrics plugin=metrics-nova.py
                       args='--scheme {{ monitoring.graphite.cluster_prefix }}.nova.hypervisor'
                       interval=3600
  notify: restart sensu-client

- name: nova state metrics check
  sensu_metrics_check: name=nova-state-metrics plugin=metrics-nova-state.py
                       args='--scheme {{ monitoring.graphite.cluster_prefix }}.nova.states'
                       interval=3600
  notify: restart sensu-client

- name: nova oversubscribe metrics check
  sensu_metrics_check: name=nova-oversubscribe-metrics plugin=metrics-nova-oversub.sh
                       args='-s {{ monitoring.graphite.cluster_prefix }}.nova.oversubscription'
                       interval=3600
  notify: restart sensu-client

- name: nova metrics
  template: src=etc/collectd/plugins/nova.conf dest=/etc/collectd/plugins/nova.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd

- name: nova sla metrics
  sensu_metrics_check: name=nova-sla-metrics plugin=metrics-os-api.py
                       args='-S nova --scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: service-list sla metrics
  sensu_metrics_check: name=service-list-sla-metrics plugin=metrics-os-api.py
                       args='-S service-list --scheme {{ monitoring.graphite.host_prefix }} -f {{ fqdn }}'
  notify: restart sensu-client

- name: nova quotas metrics
  sensu_metrics_check:
    name: compute-quotas-metrics
    plugin: metrics-nova-project-quotas.py
  notify: restart sensu-client

- name: nova usage metrics
  sensu_metrics_check:
    name: compute-usage-metrics
    plugin: metrics-nova-project-usage.py
  notify: restart sensu-client
