---
openstack_source:
  git_mirror: "{{ git_mirror|default('https://github.com/openstack') }}"
  pypi_mirror: "{{ pypi_mirror|default(None) }}"
  project_rev: "{{ project_rev|default('master') }}"
  virtualenv_base: /opt/bbc/openstack-11.0-master
  git_update: no
  rootwrap: "{{ rootwrap|default(False)|bool }}"
  system_dependencies: "{{ system_dependencies|default([]) }}"
  python_dependencies: "{{ python_dependencies|default([]) }}"

