---
swift_fqdn: "{{ fqdn }}"
endpoints:
  main: "{{ fqdn }}"
  db: "{{ undercloud_floating_ip }}"
  rabbit: "{{ undercloud_floating_ip }}"
  memcache: "{{ undercloud_floating_ip }}:11211"
  magnum: "{{ fqdn }}"
  identity_uri: https://{{ fqdn }}:35357
  auth_uri: https://{{ fqdn }}:5000/v2.0
  nova:
    name: nova
    type: compute
    description: Compute Service
    version: v2
    url:
      admin: https://{{ fqdn }}:8774
      internal: https://{{ fqdn }}:8774
      public: https://{{ fqdn }}:8774
      path: v2/%(tenant_id)s
    port:
      backend_api: 9774
      haproxy_api: 8774
    haproxy:
      health_check: 'httpchk /'
      balance: 'roundrobin'
      prefer_primary_backend: False
  glance:
    name: glance
    type: image
    description: Image Service
    url:
      admin: https://{{ fqdn }}:9292
      internal: https://{{ fqdn }}:9292
      public: https://{{ fqdn }}:9292
    port:
      backend_api: 9393
      haproxy_api: 9292
    haproxy:
      health_check: 'httpchk GET /versions'
      balance: 'source'
      prefer_primary_backend: True
  cinder:
    name: cinder
    type: volume
    description: Volume Service
    version: v1
    url:
      admin: https://{{ fqdn }}:8776
      internal: https://{{ fqdn }}:8776
      public: https://{{ fqdn }}:8776
      path: v1/%(tenant_id)s
    port:
      backend_api: 8778
      haproxy_api: 8776
    haproxy:
      health_check: 'httpchk /'
      balance: 'source'
      prefer_primary_backend: False
  cinderv2:
    name: cinderv2
    type: volume
    description: 'Volume Service v2'
    version: v2
    url:
      admin: https://{{ fqdn }}:8776
      internal: https://{{ fqdn }}:8776
      public: https://{{ fqdn }}:8776
      path: v2/%(tenant_id)s
  keystone:
    name: keystone
    type: identity
    description: 'Identity Service'
    version: v2.0
    url:
      internal: https://{{ fqdn }}:5000
      public: https://{{ fqdn }}:5000
      admin: https://{{ fqdn }}:35357
    port:
      backend_api: 5002
      haproxy_api: 5000
    haproxy:
      health_check: 'httpchk /'
      balance: 'roundrobin'
      prefer_primary_backend: False
      oidc_cookie: 'mod_auth_openidc_session prefix'
  keystone_admin:
    port:
      backend_api: 35358
      haproxy_api: 35357
    haproxy:
      health_check: 'httpchk /'
      balance: 'roundrobin'
      prefer_primary_backend: False
  keystone_legacy:
    port:
      backend_api: 5002
      haproxy_api: 5001
    haproxy:
      health_check: 'httpchk /'
      balance: 'roundrobin'
      prefer_primary_backend: False
  keystonev3:
    name: keystonev3
    type: identity
    description: 'Identity Service v3'
    version: v3
    url:
      internal: https://{{ fqdn }}:5000
      public: https://{{ fqdn }}:5000
      admin: https://{{ fqdn }}:35357
    port:
      backend_api: 5002
      haproxy_api: 5000
    haproxy:
      health_check: 'httpchk /'
      balance: 'roundrobin'
      prefer_primary_backend: False
  novnc:
    url:
      admin: https://{{ fqdn }}:6080
      internal: https://{{ fqdn }}:6080
      public: https://{{ fqdn }}:6080
    port:
      backend_api: 6081
      haproxy_api: 6080
    haproxy:
      health_check: 'tcp-check /'
      balance: 'source'
      prefer_primary_backend: True
  neutron:
    name: neutron
    type: network
    description: 'Network Service'
    url:
      admin: https://{{ fqdn }}:9696
      internal: https://{{ fqdn }}:9696
      public: https://{{ fqdn }}:9696
    port:
      backend_api: 9797
      haproxy_api: 9696
    haproxy:
      health_check: 'httpchk /'
      balance: 'source'
      prefer_primary_backend: False
  heat:
    name: heat
    type: orchestration
    description: 'Heat Orchestration API'
    version: v1
    url:
      admin: https://{{ fqdn }}:8004
      internal: https://{{ fqdn }}:8004
      public: https://{{ fqdn }}:8004
      path: v1/%(tenant_id)s
    port:
      backend_api: 8005
      haproxy_api: 8004
    haproxy:
      health_check: 'httpchk /'
      balance: 'source'
      prefer_primary_backend: False
  heat_cfn:
    name: heat-cfn
    type: cloudformation
    description: 'Heat Cloudformation API'
    version: v1
    url:
      admin: https://{{ fqdn }}:8000
      internal: https://{{ fqdn }}:8000
      public: https://{{ fqdn }}:8000
    port:
      backend_api: 8001
      haproxy_api: 8000
    haproxy:
      health_check: 'httpchk /'
      balance: 'source'
      prefer_primary_backend: False
  ceilometer:
    name: ceilometer
    type: metering
    description: 'Telemetry Service'
    url:
      admin: https://{{ fqdn }}:8777
      internal: https://{{ fqdn }}:8777
      public: https://{{ fqdn }}:8777
    port:
      backend_api: 9777
      haproxy_api: 8777
    haproxy:
      health_check: 'tcp-check /'
      balance: 'source'
      prefer_primary_backend: False
  ironic:
    name: ironic
    type: baremetal
    description: 'Ironic bare metal provisioning service'
    url:
      admin: https://{{ fqdn }}:6385
      internal: https://{{ fqdn }}:6385
      public: https://{{ fqdn }}:6385
    port:
      backend_api: 6384
      haproxy_api: 6385
    haproxy:
      health_check: 'httpchk GET /v1'
      balance: 'source'
      prefer_primary_backend: False
  swift:
    name: swift
    type: object-storage
    haproxy_vip: "{{ swift_fqdn }}"
    description: 'Object Storage Service'
    version: v1
    url:
      admin: https://{{ swift_fqdn }}:8090
      internal: https://{{ swift_fqdn }}:8090
      public: https://{{ swift_fqdn }}:8090
      path: v1/%(tenant_id)s
    port:
      haproxy_api: 8090
      cinder_backup: 8091
      proxy_api: 8080
    haproxy:
      health_check: 'httpchk HEAD /healthcheck HTTP/1.0'
      balance: 'source'
      prefer_primary_backend: False
