---
# cinder

- sensu_process_check: service=cinder-api
  notify: restart sensu-client
- sensu_process_check: service=cinder-scheduler
  notify: restart sensu-client

# glance

- sensu_process_check: service=glance-api
  notify: restart sensu-client
- sensu_process_check: service=glance-registry
  notify: restart sensu-client
- sensu_check: name=check-glance-api plugin=check-os-api.rb use_sudo=true args="--service glance"
  notify: restart sensu-client

# horizon

- sensu_process_check: service=apache2
  notify: restart sensu-client
- sensu_check: name=check-dashboard-clear-port-redirects plugin=check-http.rb args='-u http://localhost/ -r'
  notify: restart sensu-client

# keystone

- sensu_process_check: service=keystone-all
  notify: restart sensu-client
- sensu_check: name=check-keystone-api plugin=check-os-api.rb use_sudo=true args="--service keystone"
  notify: restart sensu-client

# neutron

- sensu_process_check: service=neutron-server
  notify: restart sensu-client

# haproxy

- sensu_check: name=haproxy plugin=check-procs.rb args="-p haproxy -w 5 -c 10 -W 1 -C 1"
  notify: restart sensu-client

# nova

- sensu_process_check: service={{ item }}
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
  notify: restart sensu-client

- sensu_check: name=check-nova-api plugin=check-os-api.rb use_sudo=true args="--service nova"
  notify: restart sensu-client

# rabbitmq

- sensu_process_check: service=rabbitmq
  notify: restart sensu-client
- sensu_check: name=rabbitmq-cluster plugin=check-rabbitmq-cluster.rb use_sudo=true args="--expected 2"
  notify: restart sensu-client
  when: rabbitmq_cluster
- sensu_check: name=rabbitmq-queues plugin=check-rabbitmq-queues.rb use_sudo=true
  notify: restart sensu-client

# memcached

- sensu_check: name=memcached-stats plugin=check-memcached-stats.rb args='--host={{ ansible_eth0["ipv4"]["address"] }}'
  notify: restart sensu-client

- sensu_check: name=memcached-graphite plugin=memcached-graphite.rb args='--host={{ ansible_eth0["ipv4"]["address"] }} --scheme=stats.{{ inventory_hostname  }}'
  notify: restart sensu-client
