---

- name: swift dispersion gate script
  template: src=check-swift-dispersion.sh dest=/etc/sensu/plugins/check-swift-dispersion.sh mode=0755 owner=root group=root

- sensu_check: name=swift-dispersion plugin=check-swift-dispersion.sh interval=600 occurrences=1 use_sudo=true

- name: sensu account process checks
  sensu_process_check: service={{ item }}
  with_items:
    - swift-account-auditor
    - swift-account-replicator
    - swift-account-reaper
    - swift-account-server

- name: sensu container process checks
  sensu_process_check: service={{ item }}
  with_items:
    - swift-container-replicator
    - swift-container-updater
    - swift-container-auditor
    - swift-container-sync
    - swift-container-server

- name: sensu object process checks
  sensu_process_check: service={{ item }}
  with_items:
    - swift-object-replicator
    - swift-object-updater
    - swift-object-server

- name: sensu proxy process checks
  sensu_process_check: service={{ item }}
  with_items:
    - swift-proxy
    - haproxy
    - memcached

- name: sensu check for mounted drives
  sensu_check: name=fstab-mounts plugin=check-fstab-mounts.rb args='-t xfs' interval=60

