---
repos: []
apt_repos:
  # All key_urls should be HTTPS to ensure we are retrieving the key we are expecting too
  docker:
    repo: 'https://get.docker.com/ubuntu'
    key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD8576A8BA88D21E9'
  bbg_ubuntu:
    repo: 'https://apt-mirror.openstack.blueboxgrid.com/bbg_ubuntu/ubuntu'
    key_url: 'https://apt-mirror.openstack.blueboxgrid.com/keys/bbg_ubuntu.key'
  blueboxcloud_giftwrap:
    repo: 'https://packagecloud.io/blueboxcloud/giftwrap/ubuntu/'
    key_url: 'https://packagecloud.io/gpg.key'
  hwraid:
    repo: 'http://hwraid.le-vert.net/ubuntu'
    key_url: 'http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key'
  sensu:
    repo: 'http://repos.sensuapp.org/apt'
    key_url: 'https://repos.sensuapp.org/apt/pubkey.gpg'
    distribution: 'sensu'
    components: 'main'
  haproxy:
    repo: 'http://ppa.launchpad.net/vbernat/haproxy-1.5/ubuntu'
    key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCFFB779AADC995E4F350A060505D97A41C61B9CD'
  bbg_openstack_ppa:
    repo: 'http://ppa.launchpad.net/blueboxgroup/openstack/ubuntu'
    key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC37BA5F849DE63CB'
  percona:
    repo: 'http://repo.percona.com/apt'
    key_url: 'https://www.percona.com/redir/downloads/RPM-GPG-KEY-percona'
  rabbitmq:
    repo: 'http://www.rabbitmq.com/debian/'
    key_url: 'https://www.rabbitmq.com/rabbitmq-release-signing-key.asc'
  cloud_archive:
    repo: 'http://ubuntu-cloud.archive.canonical.com/ubuntu'
  erlang:
    repo: 'http://packages.erlang-solutions.com/debian'
    key_url: 'https://packages.erlang-solutions.com/debian/erlang_solutions.asc'
  ceph:
    repo: 'http://ceph.com/debian-'
    key_url: 'https://download.ceph.com/keys/release.asc'
  mongodb:
    repo: 'http://repo.mongodb.org/apt/ubuntu'
    key_url: 'https://docs.mongodb.org/10gen-gpg-key.asc'
  logstash_forwarder:
    repo: ''
    key_url: ''
