---
- include: iptables.yml
- include: haproxy.yml
- include: keystone.yml
- include: nova.yml
- include: glance.yml
- include: neutron.yml
- include: cinder.yml
- include: novnc.yml
- include: heat.yml
  when: heat.enabled
