---
- name: swift-container service scripts
  template: src=roles/swift-common/templates/etc/init/swift-service.conf
            dest=/etc/init/swift-{{ item.service_name }}.conf mode=0644
  with_items:
    - { service_name: container-auditor, conf: container-server }
    - { service_name: container, conf: container-server }
    - { service_name: container-replicator, conf: container-server }
    - { service_name: container-sync, conf: container-server }
    - { service_name: container-updater, conf: container-server }

- name: container-server config
  template: src=etc/swift/container-server.conf mode=0640
            dest=/etc/swift/container-server.conf owner=swift group=swift
  notify: restart swift-container service

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart swift-container service
  when: (project_package.changed or git_result.changed) and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start swift-container services
  service: name={{ item }} state=started
  with_items:
    - swift-container-replicator
    - swift-container-updater
    - swift-container-auditor
    - swift-container-sync
    - swift-container
