---
dependencies:
  - role: monitoring-common
  - role: logging-config
    service: ceph
    logdata: "{{ ceph.logs }}"
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.ceph.repo }}{{ ceph.stable_release }}/ {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ceph.key_url }}'
