---
- name: pip install keystone
  action: command pip install -i {{ openstack.pypi_mirror }} /opt/stack/keystone
  register: result
  until: result|success
  retries: 3
  delay: 60

- name: restart keystone services
  restart_if_present: service=keystone
  when: restart|default('True')
