---
- name: Check if keystone user exists
  action: shell getent passwd keystone
  register: keystone_user
  ignore_errors: True
  changed_when: False

- name: keystone user
  user: name=keystone shell=/bin/false createhome=no
  when: keystone_user.rc == 0

- name: keystone user
  user: name=keystone comment=keystone shell=/bin/false system=yes home=/nonexistent createhome=no
  when: keystone_user.rc != 0

- name: WORKAROUND - keystone doesn't include babel in dependencies
  pip: name=babel

- name: get keystone source repo
  git: |
    repo={{ openstack.git_mirror }}/keystone.git 
    dest=/opt/stack/keystone 
    version={{ keystone.rev }} 
    update={{ git_update }}
  notify:
    - pip install keystone
    - restart keystone services
- meta: flush_handlers

- name: /etc/keystone
  file: dest=/etc/keystone state=directory

- name: keystone.conf
  template: src=etc/keystone/keystone.conf dest=/etc/keystone/keystone.conf mode=0644
  notify:
    - restart keystone services

- name: policy.json
  template: src=etc/keystone/policy.json dest=/etc/keystone/policy.json mode=0644
  notify:
    - restart keystone services

