---
glance:
  api_workers: 5
  rbd_store_chunk_size: 8
  registry_workers: 5
  backend_api_port: 9393
  haproxy_api_port: 9292
  sync:
    enabled: true
    listening_port: 25307
    download_limit: 0
    upload_limit: 0
    folder_rescan_interval: 600
    storage_path: /var/lib/btsync
    device_name: image-cache
    dir: /var/lib/glance/images
  store_swift: False
  store_ceph: False
  show_multiple_locations: True

  source:
    rev: 'stable/kilo'
  package:
    console_scripts:
      - glance-api
      - glance-cache-cleaner
      - glance-cache-manage
      - glance-cache-prefetcher
      - glance-cache-pruner
      - glance-control
      - glance-manage
      - glance-registry
      - glance-replicator
      - glance-scrubber

  package:
    console_scripts:
      - glance-api
      - glance-cache-cleaner
      - glance-cache-manage
      - glance-cache-prefetcher
      - glance-cache-pruner
      - glance-control
      - glance-manage
      - glance-registry
      - glance-replicator
      - glance-scrubber

  logs:
    - paths:
        - /var/log/glance/glance-api.log
      fields:
        type: openstack
        tags: glance,glance-api
    - paths:
        - /var/log/glance/glance-manage.log
      fields:
        type: openstack
        tags: glance,glance-manage
    - paths:
        - /var/log/glance/glance-registry.log
      fields:
        type: openstack
        tags: glance,glance-registry
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
