---
glance:
  api_workers: 5
  rbd_store_chunk_size: 8
  registry_workers: 5
  state_path: "{{ state_path_base }}/glance"
  sync:
    enabled: true
    listening_port: 25307
    download_limit: 0
    upload_limit: 0
    folder_rescan_interval: 600
    storage_path: /var/lib/btsync
    device_name: image-cache
    # This needs to match the leading paths from state_path above
    # and match the path listed in glance-api.conf for local image
    # store. TODO: find a way to use a variable for all of these
    dir: "{{ state_path_base }}/glance/images"
  store_smart: True
  store_swift: False
  store_ceph: False
  store_file: False
  show_multiple_locations: True
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: mysql-python }
      - { name: functools32 }
      - { name: ipaddr }
      - { name: simplegeneric }
    system_dependencies:
      - libxml2-dev
      - libmysqlclient-dev
  alternatives:
    - glance-api
    - glance-cache-cleaner
    - glance-cache-manage
    - glance-cache-prefetcher
    - glance-cache-pruner
    - glance-control
    - glance-manage
    - glance-registry
    - glance-replicator
    - glance-scrubber
  logs:
    - paths:
        - /var/log/glance/glance-api.log
      fields:
        type: openstack
        tags: glance,glance-api
    - paths:
        - /var/log/glance/glance-manage.log
      fields:
        type: openstack
        tags: glance,glance-manage
    - paths:
        - /var/log/glance/glance-registry.log
      fields:
        type: openstack
        tags: glance,glance-registry
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
