---
- apt_key: id=49DE63CB url='http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC37BA5F849DE63CB'
- apt_repository: repo='ppa:blueboxgroup/openstack' update_cache=yes cache_valid_time=3600

# FIXME(cmt): for whatever reason the PPA doesnt like the signature on openvswitch-datapath-dkms
- apt: pkg=openvswitch-datapath-dkms force=yes

- apt: pkg=openvswitch-switch
- apt: pkg=vlan
- apt: pkg=bridge-utils

- name: ovs int bridge
  ovs_bridge: name=br-int state=present

- template: src=etc/init/neutron-openvswitch-agent.conf dest=/etc/init/neutron-openvswitch-agent.conf

- service: name=neutron-openvswitch-agent state=started
