---
- name: set hostname
  hostname: name={{ hostname }}
  when: hostname is defined

- include: proxy.yml

- include: bbg-repo.yml

- name: update apt index
  apt: update_cache=yes cache_valid_time=3600

- name: python dependencies
  apt: pkg={{ item }}
  with_items:
    - python-pip
    - python-libxml2
    - python-lxml
    - python-greenlet
    - python-openssl
    - python2.7-dev
    - python-httplib2
    - python-software-properties
    - python-virtualenv
    - python-mysqldb
    - python-jinja2
    - cryptsetup
    - ipmitool
    - ntp
    - vlan
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev

- name: update pip
  pip: name=pip version=1.4.1
  when: ansible_distribution_version == "12.04"

- name: pin alembic to 0.7.0
  pip: name=alembic version=0.7.0

- name: set UTC timezone
  template: src=etc/timezone dest=/etc/timezone owner=root group=root mode=0644
  notify:
    - update timezone

- name: /opt/stack
  file: dest=/opt/stack state=directory

- include: python.yml

- include: ssl.yml tags=ssl

- include: ssh.yml

- include: networking.yml

- include: ufw.yml

# Include serial console before kernel-tuning to build serial_console_cmdline
- include: serial-console.yml tty=ttyS0

- include: ipmi.yml
  when: common.ipmi.enabled

- include: kernel-tuning.yml

- include: system-tools.yml

- include: disable-swap.yml

- include: hwraid.yml
  when: common.hwraid.enabled

# run this last so we only update if run was successful
- name: drop an motd with ursula metadata
  action: template src=etc/motd.tail dest=/etc/motd.tail mode=0644
  changed_when: False

- include: monitoring.yml tags=monitoring,common

- include: docker.yml
  when: common.docker.enabled
