---
- name: ssh agent for sudoers operations
  lineinfile: dest=/etc/sudoers insertafter="^Defaults.*$"
              line="Defaults        env_keep+=SSH_AUTH_SOCK" state=present

- name: set sshd config file
  template: src=etc/sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
    - reload-sshd

- name: add ssh private keys
  template: src=ssh-private-key dest={{ item.dest }}
            owner={{ item.owner|default("root") }}
            group={{ item.group|default("root") }} mode=0600
  with_items: "{{ common.ssh_private_keys }}"

