---
nova:
  patches:
  rev: 6bf7e78a6dc
  compute_driver: nova.virt.libvirt.LibvirtDriver
  api_workers: 5
  metadata_api_workers: 5
  cpu_allocation_ratio: 1.0
  ram_allocation_ratio: 1.0
  libvirt_cpu_model: null
  libvirt_type: kvm
  enable_ssh: False
  novnc_repo: https://github.com/kanaka/noVNC.git
  novnc_rev: 292f6a5d
