---
- name: Install XORP to provide IGMP router functionality
  apt: pkg=xorp
- template: src=etc/xorp/config.boot dest=/etc/xorp/config.boot
- lineinfile: dest=/etc/default/xorp regexp=^RUN= line=RUN=yes
- service: name=xorp state=restarted enabled=yes sleep=10
