---
- name: install neutron-data-network packages
  apt: pkg={{ item }}
  with_items:
    - dnsmasq
    - dnsmasq-utils
    - iputils-arping
    - ucarp

- include: dnsmasq.yml

- name: ensure ovs br-ex bridge present
  ovs_bridge: name=br-ex state=present
  when: neutron.plugin == 'ovs'
  notify:
    - ifup br-ex

- include: igmp-router.yml
  when: neutron.plugin == 'ml2' and 'vxlan' in neutron.tunnel_types

- name: set ovs data path agent fact
  set_fact: neutron_data_path_agent=neutron-openvswitch-agent
  when: neutron.plugin == 'ovs'

- name: set ml2 data path agent fact
  set_fact: neutron_data_path_agent=neutron-linuxbridge-agent
  when: neutron.plugin == 'ml2'

# pidfile is a hack while we wait for 'default(omit)' in ansible 1.8
- name: install neutron-data-network services
  upstart_service: name={{ item.key }}
                   user=neutron
                   cmd=/usr/local/bin/{{ item.key }}
                   pidfile="{{ item.value.pidfile|default('') }}"
                   start_on="starting {{ neutron_data_path_agent }}"
                   stop_on="stopping {{ neutron_data_path_agent }}"
                   config_dirs=/etc/neutron
                   config_files=/etc/neutron/neutron.conf,{{ item.value.config_files }}
  with_dict:
    neutron-dhcp-agent:
      config_files: /etc/neutron/dhcp_agent.ini
    neutron-l3-agent:
      config_files: /etc/neutron/l3_agent.ini
      pidfile: /var/run/enutron-l3-agent.pid
    neutron-metadata-agent:
      config_files: /etc/neutron/metadata_agent.ini

- name: start neutron-data-network services
  service: name={{ item }} state=started
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- include: ipchanged.yml

- include: monitoring.yml tags=monitoring,common
- include: logging.yml tags=logging
