---
dependencies:
  - role: endpoints
  - role: monitoring-common
  - role: logging-config
    service: cinder
    logdata: "{{ cinder.logs }}"
  - role: openstack-source
    project_name: cinder
    project_rev: "{{ cinder.source.rev }}"
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    system_dependencies: "{{ cinder.source.system_dependencies }}"
    python_dependencies: "{{ cinder.source.python_dependencies }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: cinder
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    when: openstack_install_method == 'package'
  - role: ceph-common
    when: ceph.enabled|bool
