---
- name: openstack creds
  template: src=root/stackrc dest=/root/stackrc

- name: install openstack clients
  pip: name={{ item }}
  with_items:
    - python-keystoneclient
    - python-glanceclient
    - python-novaclient
    - python-neutronclient
    - python-cinderclient
    - python-heatclient
    - python-ironicclient
    - python-swiftclient
  notify:
    - update ca certs

- name: migrate neutron services script
  template: src=usr/local/bin/migrate_neutron_services
            dest=/usr/local/bin/migrate_neutron_services mode=0755
