---
- name: create cinder volume types
  cinder_volume_type: volume_type={{ item.value.volume_type }}
                      auth_url={{ endpoints.auth_uri }}
                      login_username=admin
                      login_password={{ secrets.admin_password }}
                      login_tenant_name=admin
                      extra_specs="volume_backend_name={{ item.key }}"
  when:
    - ceph.enabled | default('False') | bool
    - item.value.enabled
  with_dict: "{{ ceph_pools }}"
  run_once: true

- name: create cinder encryption volume types
  cinder_volume_type: volume_type={{ item.volume_type }}
                      encryption_type=True
                      provider={{ item.provider }}
                      cipher={{ item.cipher }}
                      key_size={{ item.key_size }}
                      control_location={{ item.control_location }}
                      auth_url={{ endpoints.auth_uri }}
                      login_username=admin
                      login_password={{ secrets.admin_password }}
                      login_tenant_name=admin
  with_items: "{{ cinder.encrypted_volume_types }}"
  run_once: true
