---
- name: default images
  glance_image:
    name={{ item.name }}
    copy_from={{ item.url }}
    container_format=bare
    disk_format=qcow2
    auth_url=https://{{ endpoints.main }}:5001/v2.0/
    login_tenant_name=admin
    login_password={{ secrets.admin_password }}
    timeout=12000
    cacert=/opt/stack/ssl/openstack.crt
  with_items: glance.images
