---
neutron:
  l2_population: False
  vxlan:
    # The multicast prefix to use for broadcast, multicast and unknown frames
    # Consider using a larger prefix (e.g. a /24) on deployments with a
    # dedicated network infrastructure between nodes. For example with
    # group_prefix = 239.1.1.0/24, the last eight bits of the VXLAN VNID would
    # be used pick a group address within this prefix. This is a compromise
    # between network resource allocation, and efficient delivery to BUM
    # frames.
    group_prefix: 239.1.1.1
    # If using multicast, limit the L3 diameter of VXLAN multicast traffic by
    # specifying the TTL on VXLAN packets. By default we limit the TTL to one,
    # so VXLAN multicast frames are only used on the local subnet. If nodes
    # where spread between multiple subnets and intervening routers are
    # configured to route multicast, configure this value to the longest L3
    # path between nodes within the deployment.
    ttl: 1
    vni_ranges: 1:4095
  heartbeat_timeout_threshold: 30
  allow_overlapping_ips: False
  api_workers: 3
  metadata_workers: 3
  agent_down_time: 20
  report_interval: 4
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
  enable_flat_networks: False
  l3ha:
    enabled: False
    max_agents: 2
    min_agents: 2
    cidr: 169.254.192.0/18
    password: password
    interval: 2
  # Tunneling encapsulations enabled e.g. gre, vxlan
  # Including any tunnels will enable tunnling
  tunnel_types: []
  lbaas:
    # enabled can be "smart" or true / false. Smart will turn on lbaas if
    # controllers are dedicated.
    enable: smart
    interface_driver: neutron.agent.linux.interface.BridgeInterfaceDriver
    service_plugin:
      - neutron_lbaas.services.loadbalancer.plugin.LoadBalancerPluginv2
    service_provider: LOADBALANCERV2:Haproxy:neutron_lbaas.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default
  service:
    envs: []
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: mysql-python }
      - { name: "git+git://github.com/openstack/neutron-lbaas.git@stable/kilo#egg=neutron-lbaas" }
      - { name: jsonrpclib, version: "0.1.3" }
      - { name: kombu>=3.0.7 }
      - { name: amqp>=1.4.0 }
    system_dependencies:
      - libmysqlclient-dev
  alternatives:
    - neutron-cisco-apic-host-agent
    - neutron-cisco-apic-service-agent
    - neutron-db-manage
    - neutron-debug
    - neutron-dhcp-agent
    - neutron-hyperv-agent
    - neutron-ibm-agent
    - neutron-keepalived-state-change
    - neutron-l3-agent
    - neutron-lbaasv2-agent
    - neutron-linuxbridge-agent
    - neutron-metadata-agent
    - neutron-metering-agent
    - neutron-mlnx-agent
    - neutron-nec-agent
    - neutron-netns-cleanup
    - neutron-ns-metadata-proxy
    - neutron-nvsd-agent
    - neutron-openvswitch-agent
    - neutron-ovs-cleanup
    - neutron-ovsvapp-agent
    - neutron-restproxy-agent
    - neutron-rootwrap
    - neutron-rootwrap-daemon
    - neutron-rootwrap-xen-dom0
    - neutron-sanity-check
    - neutron-server
    - neutron-sriov-nic-agent
    - neutron-usage-audit
  logs:
    - paths:
        - /var/log/neutron/neutron-server.log
      fields:
        type: openstack
        tags: neutron,neutron-server
    - paths:
        - /var/log/neutron/neutron-dhcp-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-dhcp-agent
    - paths:
        - /var/log/neutron/neutron-l3-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-l3-agent
    - paths:
        - /var/log/neutron/neutron-metadata-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-metadata-agent
    - paths:
        - /var/log/neutron/neutron-lbaasv2-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-lbaasv2-agent
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  enable_external_interface: False
