---
neutron:
  rev: b5c4152ac9958e
  api_workers: 3
  agent_down_time: 20
  report_interval: 4
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
    - neutron.services.loadbalancer.plugin.LoadBalancerPlugin
