---
neutron:
  l2_population: False
  api_workers: 3
  metadata_workers: 3
  agent_down_time: 20
  report_interval: 4
  backend_api_port: 9797
  haproxy_api_port: 9696
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
  enable_flat_networks: False
  alembic_version: 0.7.0

  # Tunneling encapsulations enabled e.g. gre, vxlan
  # Including any tunnels will enable tunnling
  tunnel_types: []

  service:
    envs: []

  source:
    rev: 'stable/kilo'
  package:
    console_scripts:
      - neutron-cisco-apic-host-agent
      - neutron-cisco-apic-service-agent
      - neutron-db-manage
      - neutron-debug
      - neutron-dhcp-agent
      - neutron-hyperv-agent
      - neutron-ibm-agent
      - neutron-keepalived-state-change
      - neutron-l3-agent
      - neutron-linuxbridge-agent
      - neutron-metadata-agent
      - neutron-metering-agent
      - neutron-mlnx-agent
      - neutron-nec-agent
      - neutron-netns-cleanup
      - neutron-ns-metadata-proxy
      - neutron-nvsd-agent
      - neutron-openvswitch-agent
      - neutron-ovs-cleanup
      - neutron-ovsvapp-agent
      - neutron-restproxy-agent
      - neutron-rootwrap
      - neutron-rootwrap-daemon
      - neutron-rootwrap-xen-dom0
      - neutron-sanity-check
      - neutron-server
      - neutron-sriov-nic-agent
      - neutron-usage-audit

  package:
    console_scripts:
      - neutron-cisco-apic-host-agent
      - neutron-cisco-apic-service-agent
      - neutron-db-manage
      - neutron-debug
      - neutron-dhcp-agent
      - neutron-hyperv-agent
      - neutron-ibm-agent
      - neutron-keepalived-state-change
      - neutron-l3-agent
      - neutron-linuxbridge-agent
      - neutron-metadata-agent
      - neutron-metering-agent
      - neutron-mlnx-agent
      - neutron-nec-agent
      - neutron-netns-cleanup
      - neutron-ns-metadata-proxy
      - neutron-nvsd-agent
      - neutron-openvswitch-agent
      - neutron-ovs-cleanup
      - neutron-ovsvapp-agent
      - neutron-restproxy-agent
      - neutron-rootwrap
      - neutron-rootwrap-daemon
      - neutron-rootwrap-xen-dom0
      - neutron-sanity-check
      - neutron-server
      - neutron-sriov-nic-agent
      - neutron-usage-audit

  logs:
    - paths:
        - /var/log/neutron/neutron-server.log
      fields:
        type: openstack
        tags: neutron,neutron-server
    - paths:
        - /var/log/neutron/neutron-dhcp-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-dhcp-agent
    - paths:
        - /var/log/neutron/neutron-l3-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-l3-agent
    - paths:
        - /var/log/neutron/neutron-metadata-agent.log
      fields:
        type: openstack
        tags: neutron,neutron-metadata-agent
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
