---
- hosts: compute:network
  serial: 10
  tasks:
  - fail: msg="Stack not configured for ML2, please update group_vars/all.yml"
    when: neutron.plugin != 'ml2'

  - service: name=neutron-openvswitch-agent state=stopped enabled=no

  - service: name=nova-compute state=stopped

- hosts: network
  serial: 10
  tasks:
  - service: name={{ item }} state=stopped
    with_items:
    - neutron-dhcp-agent
    - neutron-l3-agent

- hosts: controller
  serial: 10
  tasks:
  - service: name=neutron-server state=stopped

- hosts: controller[0]
  tasks:
  - name: Backup Neutron Database
    command: mysqldump --result-file=/opt/stack/neutron-pre-ml2-upgrade.sql neutron

  - file: src=neutron-openvswitch-to-ml2-vlan-migration/files/migrate_to_ml2.py dest=/opt/stack/neutron/neutron/db/migration/migrate_to_ml2.py

  - command: python -m neutron.db.migration.migrate_to_ml2 openvswitch_to_linuxbridge mysql://neutron:{{ secrets.db_password }}@{{ endpoints.db }}/neutron?charset=utf8
    chdir: /opt/stack/neutron

  - name: Backup Migrated Neutron Database
    command: mysqldump --result-file=/opt/stack/neutron-post-ml2-upgrade.sql neutron

- hosts: compute:network:controller
  serial: 10
  tasks:
  # Configuration files from neutron-common role
  - file: dest=/etc/neutron/plugins/ml2 state=directory
  - file: dest=/etc/neutron/plugins/linuxbridge state=directory
  - template: |
      src=../roles/neutron-common/templates/etc/neutron/{{ item }}
      dest=/etc/neutron/{{ item }}
      mode=0644
    with_items:
    - neutron.conf
    - dhcp_agent.ini
    - metadata_agent.ini
    - api-paste.ini
    - l3_agent.ini
    - rootwrap.conf
    - policy.json
    - plugins/ml2/ml2_plugin.ini
    - plugins/linuxbridge/linuxbridge_conf.ini

- hosts: controller:db:compute
  serial: 10
  vars_files:
    - ../rabbitmq/defaults/main.yml
  tasks:
  - template: |
      src=../roles/nova-common/templates/etc/nova/nova.conf
      dest=/etc/nova/nova.conf
      mode=0644

- hosts: controller
  serial: 1
  tasks:
  - service: name=neutron-server state=started

- hosts: compute:network
  serial: 10
  tasks:
  - service: name=neutron-linuxbridge-agent state=started enabled=yes

- hosts: network
  serial: 10
  tasks:
  - service: name={{ item }} state=started
    with_items:
    - neutron-dhcp-agent
    - neutron-l3-agent

- hosts: compute
  serial: 10
  - service: name=nova-compute state=started
