---
- name: nova user
  user:
    name: nova
    comment: nova
    shell: /bin/sh
    system: yes
    home: "{{ nova.state_path }}"
    createhome: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096

- name: nova packages
  apt:
    pkg="{{ item }}"
  with_items: nova.install_packages

- name: create nova config dir
  file: dest=/etc/nova state=directory

- name: create nova lock dir (and parents)
  file: dest={{ nova.state_path }}/lock state=directory owner=nova

- name: create nova cache dir
  file: dest=/var/cache/nova state=directory mode=0700 owner=nova group=nova

- name: create nova log dir
  file: dest=/var/log/nova state=directory mode=2750 owner=nova group=adm

- name: Change nova log dir acl
  acl: name=/var/log/nova state=present default=yes etype={{ item.etype }} permissions={{ item.permission }}
  with_items:
    - etype: user
      permission: rw
    - etype: group
      permission: r
    - etype: other
      permission: r

- name: nova config
  action: template src={{ item }} dest=/etc/nova mode={{ 0644 if 'policy.json' in item else 0640 }}
          owner=nova group=nova
  with_fileglob: ../templates/etc/nova/*
  notify:
    - restart nova services

- name: nova sudoer
  template: |
    src=etc/sudoers.d/nova
    dest=/etc/sudoers.d/nova
    owner=root
    group=root
    mode=0440

- include: logging.yml
  tags:
    - logrotate
    - logging
  when: logging.enabled|default('True')|bool
