---
- name: nova user
  user: name=nova shell=/bin/false

- apt: pkg=python-mysqldb
- apt: pkg=python-numpy

- name: get nova source repo
  git: |
    repo={{ openstack.git_mirror }}/nova.git dest=/opt/stack/nova version={{ nova_common_rev }} depth=30
  notify:
    - pip install nova
    - nova rootwrap
    - restart nova services
- meta: flush_handlers

- file: dest=/etc/nova state=directory
- file: dest=/var/lib/nova state=directory owner=nova
- file: dest=/var/cache/nova state=directory mode=0700 owner=nova group=nova

- name: nova config
  action: template src={{ item }} dest=/etc/nova mode=0644
  with_fileglob: ../templates/etc/nova/*
  notify:
    - restart nova services

- name: nova sudoer
  template: src=etc/sudoers.d/nova dest=/etc/sudoers.d/nova owner=root group=root mode=0440
