---
- name: 'if this task fails, you must run ursula/playbooks/fix-nova-user.yml because this environment has nova user with no homedir'
  shell: '! grep nova /etc/passwd | grep nonexistent'

- name: nova user
  user: name=nova comment=nova shell=/bin/sh system=yes home=/var/lib/nova createhome=yes generate_ssh_key=yes ssh_key_bits=4096

- apt: pkg=python-numpy

- name: get nova source repo
  git: |
    repo={{ openstack.git_mirror }}/nova.git
    dest=/opt/stack/nova
    version={{ nova.rev }}
    update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install nova
    - nova rootwrap
    - restart nova services
- meta: flush_handlers

- file: dest=/etc/nova state=directory
- file: dest=/var/lib/nova state=directory owner=nova
- file: dest=/var/cache/nova state=directory mode=0700 owner=nova group=nova
- file: dest=/var/log/nova state=directory mode=0755 owner=nova group=nova

- name: nova config
  action: template src={{ item }} dest=/etc/nova mode=0644
  with_fileglob: ../templates/etc/nova/*
  notify:
    - restart nova services

- name: nova sudoer
  template: src=etc/sudoers.d/nova dest=/etc/sudoers.d/nova owner=root group=root mode=0440
