---
- name: ensure serverspec directory exists
  file: dest=/etc/serverspec/spec/localhost state=directory
        owner=root mode=0755 recurse=true

- name: serverspec checks for nova
  template: src={{ item }}
            dest=/etc/serverspec/spec/localhost/
            mode=0755
  with_fileglob: ../templates/etc/serverspec/*
