---
heat:
  enabled: True
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: mysql-python }
      - { name: functools32 }
      - { name: requests, version: 2.7.0 }
    system_dependencies:
      - libmysqlclient-dev
  alternatives:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - heat-db-setup
    - heat-engine
    - heat-keystone-setup
    - heat-keystone-setup-domain
    - heat-manage
  logs:
    - paths:
        - /var/log/heat/heat-api.log
      fields:
        type: openstack
        tags: heat,heat-api
    - paths:
        - /var/log/heat/heat-engine.log
      fields:
        type: openstack
        tags: heat,heat-engine
    - paths:
        - /var/log/heat/heat-manage.log
      fields:
        type: openstack
        tags: heat,heat-manage
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  plugin_dirs: []
