---
- name: lesscpy must be in apache PATH
  pip: name=lesscpy version=0.9j

- name: enable apache mod-headers
  apache2_module: state=present name=headers
  notify:
    - reload apache

- name: disable apache status
  template: src=etc/apache2/mods-enabled/headers.conf
            dest=/etc/apache2/mods-enabled/headers.conf
  notify:
    - reload apache

- name: create horizon config directory
  file: dest=/etc/openstack-dashboard state=directory


- name: create horizon config directory
  file: dest=/etc/openstack-dashboard state=directory

- name: openstack dashboard config (12.04)
  template: src=etc/apache2/sites-available/openstack_dashboard.conf
            dest=/etc/apache2/sites-available/openstack_dashboard
  when: ansible_distribution_version == "12.04"
  notify:
    - reload apache

- name: openstack dashboard config
  template: src=etc/apache2/sites-available/openstack_dashboard.conf
            dest=/etc/apache2/sites-available/openstack_dashboard.conf
  when: ansible_distribution_version != "12.04"
  notify:
    - reload apache

- name: enable horizon apache site
  apache2_site: name=openstack_dashboard state=present
  notify:
    - reload apache

- name: horizon local settings
  template: src=etc/openstack-dashboard/{{ item }}
            dest=/etc/openstack-dashboard/{{ item }}
            mode=0644
  with_items:
    - local_settings.py
    - __init__.py
  notify:
    - reload apache

- name: create static assets directory
  file: dest="{{ 'horizon'|ursula_package_path(openstack_package_version) }}/static"
        owner=www-data group=www-data state=directory
  when: openstack_install_method == 'package'

- name: create static assets directory
  file: dest="/opt/stack/horizon/static"
        owner=www-data group=www-data state=directory
  when: openstack_install_method == 'source'

- name: create customer-specific static assets directories
  file: dest=/etc/openstack-dashboard/{{ item }} state=directory
  with_items:
    - static
    - static/dashboard
    - static/dashboard/img
    - static/dashboard/fonts

- name: custom horizon logo
  get_url: url={{ item.url }}
           dest=/etc/openstack-dashboard/static/dashboard/{{ item.name }}
           force=True
  with_items:
    - { name: img/logo.png, url: "{{ horizon.logo_url|default('') }}"  }
    - { name: img/logo-splash.png, url: "{{ horizon.logo_url|default('') }}" }
    - { name: img/favicon.ico, url: "{{ horizon.favicon_url|default('') }}" }
  when: (horizon.logo_url is defined and horizon.favicon_url is defined)

- name: gather static assets from openstack package install
  environment:
    DJANGO_SETTINGS_MODULE: 'openstack_dashboard.settings'
    PYTHONPATH: /etc/openstack-dashboard:$PYTHONPATH
  shell: "{{ item }}"
  with_items:
    - "{{ 'horizon'|ursula_package_path(openstack_package_version) }}/bin/django-admin.py collectstatic --noinput"
    - "{{ 'horizon'|ursula_package_path(openstack_package_version) }}/bin/django-admin.py compress"
  when: openstack_install_method == 'package'

- name: gather static assets from openstack source install
  environment:
    DJANGO_SETTINGS_MODULE: 'openstack_dashboard.settings'
    PYTHONPATH: "/etc/openstack-dashboard:/opt/stack/horizon:$PYTHONPATH"
  shell: "{{ item }}"
  with_items:
    - "{{ openstack_source.virtualenv_base }}/horizon/bin/django-admin.py collectstatic --noinput"
    - "{{ openstack_source.virtualenv_base }}/horizon/bin/django-admin.py compress"
  when: openstack_install_method == 'source'

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart apache
  when: (project_package.changed or git_result.changed) and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: ensure apache started
  service: name=apache2 state=started

- name: Permit HTTP and HTTPS
  ufw: rule=allow to_port={{ item }} proto=tcp
  tags: ufw
  with_items:
  - 80
  - 443

- meta: flush_handlers

- name: ensure apache is enabled
  service: name=apache2 state=started enabled=true

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool

- include: logging.yml
  tags:
    - logrotate
    - logging
  when: logging.enabled|default('True')|bool

- include: serverspec.yml
  tags:
    - serverspec
  when: serverspec.enabled|default('False')|bool
