---
- apt: pkg={{ item }}
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - python-dev

- name: lesscpy must be in apache PATH
  pip: name=lesscpy version=0.9j

- name: get horizon source repo
  git: |
    repo={{ openstack.git_mirror}}/horizon.git dest=/opt/stack/horizon version={{ horizon.rev }}
  notify:
    - setup horizon venv
    - compress horizon assets

- name: add python-memcached to horizon requirements
  lineinfile: dest=/opt/stack/horizon/requirements.txt regexp=^python-memcached line=python-memcached
  notify:
    - setup horizon venv

- name: disable apache status
  command: a2dismod status
  notify:
    - restart apache

- template: src=etc/apache2/ports.conf dest=/etc/apache2/ports.conf
  notify:
    - restart apache

- name: disable default apache site
  command: a2dissite 000-default
  notify:
    - restart apache

- template: |
    src=etc/apache2/sites-available/openstack_dashboard.conf
    dest=/etc/apache2/sites-available/openstack_dashboard
  notify:
    - restart apache

- name: enable horizon apache site
  command: a2ensite openstack_dashboard
  notify:
    - restart apache

# static asset directories
- file: |
    dest=/opt/stack/horizon/static
    state=directory
    owner=www-data
    group=www-data
    mode=0755
- file: |
    dest=/opt/stack/horizon/static/dashboard
    state=directory
    owner=www-data
    group=www-data
    mode=0755

- template: |
    src=opt/stack/horizon/openstack_dashboard/local/local_settings.py
    dest=/opt/stack/horizon/openstack_dashboard/local/local_settings.py
    mode=0644
  notify:
    - restart apache

- name: custom horizon logo
  get_url: url={{ horizon.logo_url }} dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/logo.png mode=0644 force=yes

- name: custom horizon splash logo
  get_url: url={{ horizon.logo_url }} dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/logo-splash.png mode=0644 force=yes

- name: custom horizon favicon
  get_url: url={{ horizon.favicon_url }} dest=/opt/stack/horizon/openstack_dashboard/static/dashboard/img/favicon.ico force=yes

- name: put images and fonts where apache can find them
  file: |
    src=/opt/stack/horizon/openstack_dashboard/static/dashboard/{{ item }}
    dest=/opt/stack/horizon/static/dashboard/{{ item }}
    state=link
    owner=www-data
    group=www-data
  with_items:
    - img
    - fonts

- service: name=apache2 state=started

- name: Permit HTTP (redirect to HTTPS for Horizon)
  command: ufw allow 80/tcp

- name: Permit HTTPS (Horizon)
  command: ufw allow 443/tcp
