---
dependencies:
  - role: endpoints
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.cloud_archive.repo }} {{ ansible_distribution_release }}-updates/kilo main'
        key_package: ubuntu-cloud-keyring
    when: ansible_distribution_version == "12.04"
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: nova
    logdata: "{{ nova.logs }}"
  - role: openstack-source
    project_name: nova
    project_rev: "{{ nova.source.rev }}"
    rootwrap: True
    alternatives: "{{ nova.alternatives }}"
    system_dependencies: "{{ nova.source.system_dependencies }}"
    python_dependencies: "{{ nova.source.python_dependencies }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: nova
    rootwrap: True
    alternatives: "{{ nova.alternatives }}"
    when: openstack_install_method == 'package'
