---
dependencies:
  - role: endpoints
  - role: monitoring-common
  - role: logging-config
    service: horizon
    logdata: "{{ horizon.logs }}"
  - role: openstack-source
    project_name: horizon
    git_mirror: "https://github.com/blueboxgroup"
    project_rev: "{{ horizon.source.rev }}"
    system_dependencies: "{{ horizon.source.system_dependencies }}"
    python_dependencies: "{{ horizon.source.python_dependencies }}"
    additional_handlers: [ "compress horizon assets" ]
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: horizon
    when: openstack_install_method == 'package'
